// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRnJo-RvTvH2i9Ukd4BPyhQfrR6x-tLeY',
    appId: '1:675866104387:web:7c4785fef28599de5fbaf6',
    messagingSenderId: '675866104387',
    projectId: 'sanalira-case-study',
    authDomain: 'sanalira-case-study.firebaseapp.com',
    storageBucket: 'sanalira-case-study.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNF0_lunWY7hd__bv3rWepMHYD-iXA6X4',
    appId: '1:675866104387:android:d3574df311c0f0925fbaf6',
    messagingSenderId: '675866104387',
    projectId: 'sanalira-case-study',
    storageBucket: 'sanalira-case-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRfpxyEiTQ8C53S94ygmDc3eXmfbALZas',
    appId: '1:675866104387:ios:8c3ab5ae51feb4ec5fbaf6',
    messagingSenderId: '675866104387',
    projectId: 'sanalira-case-study',
    storageBucket: 'sanalira-case-study.appspot.com',
    iosClientId: '675866104387-kkcceeg5g9mkjk1tlffg6suvv1ghuspc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanalira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRfpxyEiTQ8C53S94ygmDc3eXmfbALZas',
    appId: '1:675866104387:ios:8c3ab5ae51feb4ec5fbaf6',
    messagingSenderId: '675866104387',
    projectId: 'sanalira-case-study',
    storageBucket: 'sanalira-case-study.appspot.com',
    iosClientId: '675866104387-kkcceeg5g9mkjk1tlffg6suvv1ghuspc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanalira',
  );
}
